use crate::domain::value_objects::{Money};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventOrder {
    pub exchange: String,
    pub status: String,
    pub type_: String,
    pub symbol: String,
    pub side: String,
    pub order_type: String,
    pub fee_type: Option<String>,
    pub liquidity: Option<String>,
    pub price: Option<Money>,
    pub order_id: String,
    pub client_oid: Option<String>,
    pub trade_id: Option<String>,
    pub origin_size: Option<Money>,
    pub size: Option<Money>,
    pub filled_size: Option<Money>,
    pub match_size: Option<Money>,
    pub match_price: Option<Money>,
    pub canceled_size: Option<Money>,
    pub old_size: Option<Money>,
    pub remain_size: Option<Money>,
    pub remain_funds: Option<Money>,
    pub order_time: i64,
    pub ts: i64,
    pub updated_at: DateTime<Utc>,
}

impl EventOrder {
    pub fn new(
        exchange: String,
        status: String,
        type_: String,
        symbol: String,
        side: String,
        order_type: String,
        fee_type: Option<String>,
        liquidity: Option<String>,
        price: Option<Money>,
        order_id: String,
        client_oid: Option<String>,
        trade_id: Option<String>,
        origin_size: Option<Money>,
        size: Option<Money>,
        filled_size: Option<Money>,
        match_size: Option<Money>,
        match_price: Option<Money>,
        canceled_size: Option<Money>,
        old_size: Option<Money>,
        remain_size: Option<Money>,
        remain_funds: Option<Money>,
        order_time: i64,
        ts: i64,
        updated_at: DateTime<Utc>,
    ) -> Self {
        Self {
            exchange,
            status,
            type_,
            symbol,
            side,
            order_type,
            fee_type,
            liquidity,
            price,
            order_id,
            client_oid,
            trade_id,
            origin_size,
            size,
            filled_size,
            match_size,
            match_price,
            canceled_size,
            old_size,
            remain_size,
            remain_funds,
            order_time,
            ts,
            updated_at,
        }
    }
}
