use crate::domain::value_objects::{Money};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Symbol {
    pub exchange: String,
    pub symbol: String,
    pub symbol_name: String,
    pub base_currency: String,
    pub quote_currency: String,
    pub fee_currency: String,
    pub market: String,
    pub base_min_size: Money,
    pub quote_min_size: Money,
    pub base_max_size: Money,
    pub quote_max_size: Money,
    pub base_increment: Money,
    pub quote_increment: Money,
    pub price_increment: Money,
    pub price_limit_rate: String,
    pub min_funds: Option<Money>,
    pub is_margin_enabled: bool,
    pub enable_trading: bool,
    pub fee_category: i16,
    pub maker_fee_coefficient: f64,
    pub taker_fee_coefficient: f64,
    pub st: bool,
    pub updated_at: DateTime<Utc>,
}

impl Symbol {
    pub fn new(
        exchange: String,
        symbol: String,
        symbol_name: String,
        base_currency: String,
        quote_currency: String,
        fee_currency: String,
        market: String,
        base_min_size: Money,
        quote_min_size: Money,
        base_max_size: Money,
        quote_max_size: Money,
        base_increment: Money,
        quote_increment: Money,
        price_increment: Money,
        price_limit_rate: String,
        min_funds: Option<Money>,
        is_margin_enabled: bool,
        enable_trading: bool,
        fee_category: i16,
        maker_fee_coefficient: f64,
        taker_fee_coefficient: f64,
        st: bool,
        updated_at: DateTime<Utc>,
    ) -> Self {
        Self {
            exchange,
            symbol,
            symbol_name,
            base_currency,
            quote_currency,
            fee_currency,
            market,
            base_min_size,
            quote_min_size,
            base_max_size,
            quote_max_size,
            base_increment,
            quote_increment,
            price_increment,
            price_limit_rate,
            min_funds,
            is_margin_enabled,
            enable_trading,
            fee_category,
            maker_fee_coefficient,
            taker_fee_coefficient,
            st,
            updated_at,
        }
    }
}
